 # Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
source 'https://github.com/FMYang/FMPodSpec.git'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
#  pod 'FMFramework', :path => '../../FMFramework'
  pod 'FMFramework', '0.0.17'

end
