 # Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Example' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example
#  pod 'FMFramework', :path => '../../FMFramework'
  pod 'FMFramework', :git => 'https://github.com/FMYang/FMFramework.git', :tag => '0.0.2'/Volumes/yfm的移动硬盘/项目/YTC/project/consumer/YTCConsumerProject/fastlane/Fastfile

end
