
ProjectName="FMFramework"
ProjectPath="./FMFramework.podspec"

desc '升级私有库脚本'
lane :release do |options|

tagNum = options[:tag]
message = options[:message]

pod_lib_lint(use_bundle_exec: false)

# 更新spec版本号
version_bump_podspec(path: ProjectPath, version_number: tagNum)

git_add(path: ".")
git_commit(path: ".", message: message)
push_to_git_remote

if git_tag_exists(tag: tagNum)
      # 版本已经存在
      raise "版本#{tagNum}已经存在，请检查版本号，修改后重新提交" 
end

# 打tag
add_git_tag(tag: tagNum)

# 上传tag
push_git_tags

# 返回上一个目录
Dir.chdir "../"
# 使用shell脚本上传podspec
system 'pod repo push https://github.com/FMYang/FMPodSpec.git FMFramework.podspec --allow-warnings'

end

lane :test do
 
end
