
ProjectName="FMFramework"
ProjectPath="./FMFramework.podspec"
PodSpecDir="/Users/fmy/zy/FMPodSpec/FMFramework/"

desc '升级私有库脚本'
lane :release do |options|

tagNum = options[:tag]
message = options[:message]

# 更新spec版本号
version_bump_podspec(path: ProjectPath, version_number: tagNum)

git_add(path: ".")
git_commit(path: ".", message: message)
push_to_git_remote

if git_tag_exists(tag: tagNum)
      # 版本存在，删除对应 tag
      remove_git_tag(tag: tagNum)
end

add_git_tag(
	tag: tagNum
)

push_git_tags

# pod_lib_lint(allow_warnings: true)

`cd ..`
`pod repo push fmyang FMFramework.podspec`

end

lane :DirTest do |options|
	# `pod repo push fmyang FMFramework.podspec`
	`cd ..`
	`pod repo push fmyang FMFramework.podspec`
end